# Generated by Django 3.0.4 on 2020-03-29 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='profile_creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='genre',
            field=models.CharField(choices=[('EDM', 'Edm'), ('R&B', 'R&B'), ('HIP-HOP', 'Hip-Hop'), ('LATIN', 'Latin'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='performer_category',
            field=models.CharField(choices=[('DJ', 'Dj'), ('SINGER', 'Singer'), ('BAND', 'Band'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
